routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('layouts.frontend.default');
// });

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/detail-berita/{slug}', 'DetailController@index')
    ->name('detail.berita');

Route::get('/admin', 'Admin\DashboardController@index')
    ->name('admin');

Route::get('/detailpegawaiprofile', 'DetailPegawaiProfileController@index')
    ->name('detail.pegawai');

Route::get('/detailpenduduk', 'DetailPendudukController@index')
    ->name('detail.penduduk');

Route::get('/organisasi', 'OrganisasiController@index')
    ->name('organisasi');

Route::resource('tags', 'Admin\TagNewsController');
Route::resource('news', 'Admin\NewsController');
Route::resource('image', 'Admin\ImageController');
Route::resource('pegawaiprofile', 'Admin\PegawaiProfileController');
Route::resource('penduduk', 'Admin\PendudukController');
Route::resource('struktur', 'Admin\struktur_organisasiController');


Auth::routes();
// Auth::routes(['register' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = "tags";
    protected $fillable = [ 'tag_name' ];

    protected $hidden = [];

    public function news()
    {
        return $this->belongsToMany('App\Models\News', 'news_tag', 'news_id', 'tag_id');
    }
}

resources/views/pages/backend/tags/create.blade.php
@extends('layouts.backend.master')

@section('title', 'Buat Tags')
@push('after-style')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.6.2/tinymce.min.js"></script>
@endpush

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-center mb-4">
        <h1 class="h3 mb-0 text-gray-800">Form Tambah Tags</h1>
    </div>

    <!-- Munculkan error -->
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

  <!-- Card Form tambah berita -->
  <div class="card shadow">
    <div class="card-body">
        <form action="{{ route('tags.store')}}" method="POST" enctype="multipart/form-data">
         @csrf
            <div class="form-group">
                <label for="tag_name">kategori</label>
                <input type="text" class="form-control" name="tag_name" placeholder="tag name" 
                       value="{{ old('tag_name')}}" required>
            </div>            
            <button type="submit" class="btn btn-primary btn-block">Simpan</button>
        </form>
     </div>
    </div>
</div>
@endsection

@push('after-scripts')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: 'textarea.my-editor',
    relative_urls: false,
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table directionality",
      "emoticons template paste textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    file_picker_callback : function(callback, value, meta) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?editor=' + meta.fieldname;
      if (meta.filetype == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.openUrl({
        url : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no",
        onMessage: (api, message) => {
          callback(message.content);
        }
      });
    }
  };

  tinymce.init(editor_config);
</script>
@endpush

resources/views/pages/backend/tags/edit.blade.php
@extends('layouts.backend.master')

@section('title', 'Ubah Berita')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit kategori  {{ $item->tag_name }} </h1>
    </div>

    <!-- Munculkan error -->
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

  <!-- Card Form tambah berita -->
  <div class="card shadow">
    <div class="card-body">
        <form action="{{ route('tags.update', $item->id) }}" method="POST" enctype="multipart/form-data">
         @method('PUT')
         @csrf
            <div class="form-group">
                <label for="tag_name">Kategori</label>
                <input type="text" class="form-control" name="tag_name" placeholder="tag_name" value="{{ $item->tag_name }}" required>
            </div>
            <button type="submit" class="btn btn-primary btn-block">Ubah</button>
        </form>
     </div>
    </div>
</div>
<!-- /.container-fluid -->

@endsection

resources/views/pages/backend/tags/index.blade.php
@extends('layouts.backend.master')

@section('title', 'Kategori Berita')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex justify-content-end mb-4">
        <a href="{{ route('tags.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-100"></i> Tambah Kategori Berita
        </a>
    </div>

    <div class="d-sm-flex d-flex justify-content-center">
        <h1 class="h3 mb-0 text-gray-800">Daftar Kategori Berita</h1>
    </div>

    <div class="row">
        <div class="card-body">
            @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ session('success') }}
            </div>
            @endif

            <div class="table-responsive">
                <table id="tagNews" 
                       class="table table-bordered table-hover" 
                       width="100%" cellspacing="0" data-form="deleteForm">
                    <thead class="thead-dark text-center">
                        <tr>
                            <th style="width: 5%;">NO</th>
                            <th>Tags</th>                         
                            <th style="width: 18%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php $no = 0;?>
                    @forelse($tags as $tag)
                    <?php $no++ ;?>
                        <tr>
                            <td>{{ $no }}</td>
                            <td>{{ $tag->tag_name }}</td>                                                  
                            <td style="text-align:center;">                                
                                <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="edit">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <form action="{{ route('tags.destroy', $tag->id) }}"
                                    method="POST" class="d-inline form-delete">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger" data-toggle="tooltip" data-placement="bottom" title="delete">
                                        <i class="fa fa-trash" ></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                        <td colspan="7" class="text-center">
                            Belum Ada Kategori
                        </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@include('includes.backend.ModalDelete')
@endsection

@push('after-scripts')
    <script src="{{ asset('sbadmin2/plugins/datatables/jquery.dataTables.js ') }}"></script>
    <script src="{{ asset('sbadmin2/plugins/datatables-bs4/js/dataTables.bootstrap4.js ') }}"></script>
    <script>
    $(function () {
        $("#tagNews").DataTable();
    });
    </script>
@endpush