routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('layouts.frontend.default');
// });

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/detail-berita/{slug}', 'DetailController@index')
    ->name('detail.berita');

Route::get('/admin', 'Admin\DashboardController@index')
    ->name('admin');

Route::get('/detailpegawaiprofile', 'DetailPegawaiProfileController@index')
    ->name('detail.pegawai');

Route::get('/detailpenduduk', 'DetailPendudukController@index')
    ->name('detail.penduduk');

Route::get('/organisasi', 'OrganisasiController@index')
    ->name('organisasi');

Route::resource('tags', 'Admin\TagNewsController');
Route::resource('news', 'Admin\NewsController');
Route::resource('image', 'Admin\ImageController');
Route::resource('pegawaiprofile', 'Admin\PegawaiProfileController');
Route::resource('penduduk', 'Admin\PendudukController');
Route::resource('struktur', 'Admin\struktur_organisasiController');


Auth::routes();
// Auth::routes(['register' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/backend/ModalDelete.blade.php
<div class="modal" id="confirm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-warning">
                <h4 class="modal-title">Delete Confirmation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>               
            </div>
            <div class="modal-body">
                <p>Apakah Anda Yakin untuk Menghapus ?</p>
            </div>
            <div class="modal-footer bg-secondary">
                <button type="button" class="btn btn-md btn-primary" id="delete-btn">Delete</button>
                <button type="button" class="btn btn-md btn-success" data-dismiss="modal">Tidak</button>
            </div>
        </div>
    </div>
</div>

resources/views/includes/backend/footer.blade.php
<footer class="sticky-footer bg-white" >
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <strong><span>Copyright &copy; All Right Reserved | Kelurahan Sanbercode | 2021</span></strong>
        </div>
    </div>
</footer>

resources/views/includes/backend/meta.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>@yield('title')</title>

resources/views/includes/backend/navbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Title -->
<form
    class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
    logged in as username <strong style="margin-left:10px;"> 
        {{ auth()->user()->name }} 
    </strong>
    </div>
</form>

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
        </a>
        <!-- Dropdown - Messages -->
        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
            aria-labelledby="searchDropdown">
            <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small"
                        placeholder="Search for..." aria-label="Search"
                        aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small text-uppercase">
                    {{ Auth::user()->pegawai_profile->nama_lengkap ?? 'nama lengkap belum di isi'}}
                <strong>
                    ({{ Auth::user()->pegawai_profile->jabatan ?? 'jabatan belum di isi' }})
                </strong>

            </span>
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">

            </span>

            <img class="img-profile rounded-circle"
                src="{{ Storage::url(Auth::user()->pegawai_profile->photo ?? 'no data' ) }}" style="object-fit:cover;">
                <!-- src="{{ asset('sbadmin2/img/undraw_profile.svg') }}"> -->
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
            aria-labelledby="userDropdown">
            <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
            </a>
            <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
            </a>
        </div>
    </li>

</ul>

</nav>

resources/views/includes/backend/scripts.blade.php
<!-- Bootstrap core JavaScript-->
<script src="{{ asset('sbadmin2/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('sbadmin2/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

<!-- Core plugin JavaScript-->
<script src="{{ asset('sbadmin2/vendor/jquery-easing/jquery.easing.min.js') }}"></script>

<!-- Custom scripts for all pages-->
<script src="{{ asset('sbadmin2/js/sb-admin-2.min.js') }}"></script>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
    })
</script>

<script>
    $('table[data-form="deleteForm"]').on('click', '.form-delete', function(e){
        e.preventDefault();
        var $form=$(this);
        $('#confirm').modal({ backdrop: 'static', keyboard: false })
            .on('click', '#delete-btn', function(){
                $form.submit();
            });
    });
</script>

resources/views/includes/backend/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <img class="img-profile img-fluid"
        src="{{ asset('sbadmin2/img/logo1.png') }}">
        <!-- <div class="sidebar-brand-text mx-3">Kelurahan Sanbercode</div> -->
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ route('admin') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('news.index') }}">
        <i class="fas fa-newspaper"></i>
            <span>Berita</span></a>
    </li>

     <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('image.index') }}">
        <i class="fas fa-fw fa-folder"></i>
            <span>Gambar</span></a>
    </li>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link" href="{{ route('tags.index') }}">
        <i class="fas fa-fw fa-folder"></i>
            <span>Kategori/Tags</span></a>
    </li>


    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Profile</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href=" {{route('pegawaiprofile.index')}} ">Data Pegawai</a>
                <a class="collapse-item" href="{{ route('struktur.index') }}">Struktur Organisasi</a>
            </div>
        </div>
    </li>


    <!-- Nav Item - Pages Collapse Menu -->
    <!-- <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-qrcode"></i>
            <span>Informasi</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href=" ">Data Penduduk</a>
            </div>
        </div>
    </li> -->

    <li class="nav-item">
        <a class="nav-link" href="{{ route('penduduk.index') }} ">
        <i class="fas fa-fw fa-folder"></i>
            <span>Data Penduduk</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

resources/views/includes/backend/styles.blade.php
<!-- Custom fonts for this template-->
<link href="{{ asset('sbadmin2/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{{ asset('sbadmin2/css/sb-admin-2.min.css') }}" rel="stylesheet">

 <!-- Data Tables -->
 <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.css"/>