routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', function () {
//     return view('layouts.frontend.default');
// });

Route::get('/', 'HomeController@index')
    ->name('home');

Route::get('/detail-berita/{slug}', 'DetailController@index')
    ->name('detail.berita');

Route::get('/admin', 'Admin\DashboardController@index')
    ->name('admin');

Route::get('/detailpegawaiprofile', 'DetailPegawaiProfileController@index')
    ->name('detail.pegawai');

Route::get('/detailpenduduk', 'DetailPendudukController@index')
    ->name('detail.penduduk');

Route::get('/organisasi', 'OrganisasiController@index')
    ->name('organisasi');

Route::resource('tags', 'Admin\TagNewsController');
Route::resource('news', 'Admin\NewsController');
Route::resource('image', 'Admin\ImageController');
Route::resource('pegawaiprofile', 'Admin\PegawaiProfileController');
Route::resource('penduduk', 'Admin\PendudukController');
Route::resource('struktur', 'Admin\struktur_organisasiController');


Auth::routes();
// Auth::routes(['register' => false]);

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/Penduduk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Penduduk extends Model
{
    protected $table = "penduduk";

    protected $fillable = [
        'nama_desa',
        'jumlah_pria',
        'jumlah_wanita',
        'jumlah_kematian',
        'jumlah_kelahiran',
        'keterangan'
    ];
}

app/Http/Controllers/Admin/PendudukController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PendudukRequest;
use Illuminate\Http\Request;
use App\Models\Penduduk;
use RealRashid\SweetAlert\Facades\Alert;
use PDF;

class PendudukController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Penduduk::all();
        return view('pages.backend.penduduk.index',compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.backend.penduduk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PendudukRequest $request)
    {
        $data = $request->all();
        Penduduk::create($data);

        Alert::success('Success', 'Berhasil menambahkan Data Penduduk terbaru');
        return redirect()->route('penduduk.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $items = Penduduk::findOrFail($id);
        // return view('pages.backend.penduduk.show', compact('items'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $items = Penduduk::findOrFail($id);
        return view('pages.backend.penduduk.edit', compact('items'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PendudukRequest $request, $id)
    {
        $data = $request->all();

        $items = Penduduk::findOrFail($id);
        $items->update($data);

        Alert::info('Success', 'Berhasil Update Data Penduduk');
        return redirect()->route('penduduk.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $items = Penduduk::findOrFail($id);
        $items->delete();

        Alert::info('Success', 'Berhasil Delete Data Penduduk');
        return redirect()->route('penduduk.index');
    }
}

resources/views/pages/backend/penduduk/create.blade.php
@extends('layouts.backend.master')
@section('title', 'Tambah Data Penduduk')

@section('title', 'Tambah Penduduk')
@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-center mb-4">
        <h1 class="h3 mb-0 text-gray-800">Form Data Penduduk</h1>
    </div>

    <!-- Munculkan error -->
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif


    <div class="card shadow">
        <div class="card-body">
            <form action="{{ route('penduduk.store')}}" method="POST" enctype="multipart/form-data">
             @csrf
                <div class="form-group">
                    <label for="nama_desa">RT/Lingkungan</label>
                    <input type="text" class="form-control" name="nama_desa" placeholder="Isi Nama Desa" value="{{ old('title')}}" required>
                </div>
                <div class="form-group">
                    <label for="jumlah_pria">Jumlah Pria</label>
                    <input type="text" class="form-control" name="jumlah_pria" placeholder="Isi Jumlah Pria" value="{{ old('location')}}" required>
                </div>
                <div class="form-group">
                    <label for="jumlah_wanita">Jumlah Wanita</label>
                    <input type="text" class="form-control" name="jumlah_wanita" placeholder="Isi Jumlah Wanita" value="{{ old('location')}}" required>
                </div>
                <div class="form-group">
                    <label for="jumlah_kematian">Jumlah Kematian</label>
                    <input type="text" class="form-control" name="jumlah_kematian" placeholder="Isi Jumlah Kematian" value="{{ old('location')}}" required>
                </div>
                <div class="form-group">
                    <label for="jumlah_kelahiran">Jumlah Kelahiran</label>
                    <input type="text" class="form-control" name="jumlah_kelahiran" placeholder="Isi Jumlah Kelahiran" value="{{ old('location')}}" required>
                </div>
                <div class="form-group">
                    <label class="Keterangan" for="keterangan">Keterangan</label>
                    <textarea name="keterangan" id="keterangan" class="form-control" >{{ old('keterangan') }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Simpan</button>
            </form>
         </div>
        </div>
</div>

@endsection

resources/views/pages/backend/penduduk/edit.blade.php
@extends('layouts.backend.master')
@section('title', 'Edit Data Penduduk')

@section('title', 'Ubah Penduduk')
@section('content')

<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Penduduk Desa {{ $items->nama_desa }} </h1>
    </div>

    <!-- Munculkan error -->
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

  <!-- Card Form tambah berita -->
  <div class="card shadow">
    <div class="card-body">
        <form action="{{ route('penduduk.update', $items->id)}}" method="POST" enctype="multipart/form-data">
         @method('PUT')
         @csrf
         <div class="form-group">
            <label for="nama_desa">Nama Desa</label>
            <input type="text" class="form-control" name="nama_desa" value="{{ $items->nama_desa}}" required>
        </div>
        <div class="form-group">
            <label for="jumlah_pria">Jumlah Pria</label>
            <input type="text" class="form-control" name="jumlah_pria" value="{{ $items->jumlah_pria }}" required>
        </div>
        <div class="form-group">
            <label for="jumlah_wanita">Jumlah Wanita</label>
            <input type="text" class="form-control" name="jumlah_wanita" value="{{ $items->jumlah_wanita }}" required>
        </div>
        <div class="form-group">
            <label for="jumlah_kematian">Jumlah Kematian</label>
            <input type="text" class="form-control" name="jumlah_kematian" value="{{ $items->jumlah_kematian }}" required>
        </div>
        <div class="form-group">
            <label for="jumlah_kelahiran">Jumlah Kelahiran</label>
            <input type="text" class="form-control" name="jumlah_kelahiran" value="{{ $items->jumlah_kelahiran }}" required>
        </div>
        <div class="form-group">
            <label class="Keterangan" for="keterangan">Keterangan</label>
            <textarea name="keterangan" id="keterangan" class="form-control" >{{ $items->keterangan }}</textarea>
        </div>
            <button type="submit" class="btn btn-primary btn-block">Ubah</button>
        </form>
     </div>
    </div>


</div>
<!-- /.container-fluid -->

@endsection

resources/views/pages/backend/penduduk/index.blade.php
@extends('layouts.backend.master')
@section('title', 'Penduduk')

@section('title', 'List Penduduk')
@section('content')
    <!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex justify-content-end mb-4">
        <a href="{{ route('penduduk.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-100"></i> Tambah Data Penduduk
        </a>
    </div>

    <div class="d-sm-flex d-flex justify-content-center">
        <h1 class="h3 mb-0 text-gray-800">Data Penduduk</h1>
    </div>

    <div class="row">
        <div class="card-body">
            @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ session('success') }}
            </div>
            @endif

            <div class="table-responsive">
                <table id="tableNews" class="table table-bordered table-hover" width="100%" cellspacing="0" data-form="deleteForm">
                    <thead class="thead-dark text-center">
                        <tr>
                            <th style="width: 5%;">NO</th>
                            <th style="width: 15%;">RT/Lingkungan</th>
                            <th style="width: 10%;">Jumlah Pria</th>
                            <th style="width: 10%;">Jumlah Wanita</th>
                            <th style="width: 10%;">Jumlah Kematian</th>
                            <th style="width: 10%;">Jumlah Kelahiran</th>
                             <th style="width: 18%;">Keterangan</th>
                             <th style="width: 18%;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php $no = 0;?>
                    @forelse ($items as $value)
                    <?php $no++ ;?>
                        <tr>
                            <td>{{ $no }}</td>
                            <td>{{ $value->nama_desa }}</td>
                            <td>{{ $value->jumlah_pria }}</td>
                            <td>{{ $value->jumlah_wanita }}</td>
                            <td>{{ $value->jumlah_kematian }}</td>
                            <td>{{ $value->jumlah_kelahiran }}</td>
                            <td>{{ $value->keterangan }}</td>
                            <td style="text-align:center;">

                                <a href="{{ route('penduduk.edit', $value->id) }}" class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="edit">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <form action="{{ route('penduduk.destroy', $value->id) }}"
                                    method="POST" class="d-inline form-delete">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger" data-toggle="tooltip" data-placement="bottom" title="delete">
                                        <i class="fa fa-trash" ></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="text-center">
                                Belum Ada Data Penduduk
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.container-fluid -->
@include('includes.backend.ModalDelete')

@endsection

@push('after-scripts')
    <script src="{{ asset('sbadmin2/plugins/datatables/jquery.dataTables.js ') }}"></script>
    <script src="{{ asset('sbadmin2/plugins/datatables-bs4/js/dataTables.bootstrap4.js ') }}"></script>
    <script>
    $(function () {
        $("#tableNews").DataTable();
    });
    </script>
@endpush

resources/views/pages/backend/penduduk/show.blade.php
@extends ('layouts.backend.master')

@section('title', 'Detail Berita')

@section('content')
    <div class="card p-5">
        <div class="d-sm-flex justify-content-end mb-4">
            <a href="{{ route('penduduk.index') }}" class="btn btn-primary mt-3">Kembali</a>
        </div>
        <div class="card-header">
            <strong>Detail Data Penduduk</strong>
        </div>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Nama Desa : {{ $items->nama_desa}}</h5>
                <h5 class="card-title">Jumlah Pria : {{ $items->jumlah_pria }} Jiwa</h5>
                <h5 class="card-title">Jumlah Wanita : {{ $items->jumlah_wanita }} Jiwa</h5>
                <h5 class="card-text">Jumlah Kematian : {{$items->jumlah_kematian}} Jiwa</h5>
                <h5 class="card-text">Jumlah Kelahiran : {{$items->jumlah_kelahiran}} Jiwa</h5>
                <h5 class="card-text">Keterangan : {{$items->keteragan}}</h5>
            </div>
        </div>
    </div>
@endsection